// Code generated by protoc-gen-go.
// source: ql2.proto
// DO NOT EDIT!

package ql2

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type VersionDummy_Version int32

const (
	VersionDummy_V0_1 VersionDummy_Version = 1063369270
)

var VersionDummy_Version_name = map[int32]string{
	1063369270: "V0_1",
}
var VersionDummy_Version_value = map[string]int32{
	"V0_1": 1063369270,
}

func (x VersionDummy_Version) Enum() *VersionDummy_Version {
	p := new(VersionDummy_Version)
	*p = x
	return p
}
func (x VersionDummy_Version) String() string {
	return proto.EnumName(VersionDummy_Version_name, int32(x))
}
func (x VersionDummy_Version) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *VersionDummy_Version) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(VersionDummy_Version_value, data, "VersionDummy_Version")
	if err != nil {
		return err
	}
	*x = VersionDummy_Version(value)
	return nil
}

type Query_QueryType int32

const (
	Query_START    Query_QueryType = 1
	Query_CONTINUE Query_QueryType = 2
	Query_STOP     Query_QueryType = 3
)

var Query_QueryType_name = map[int32]string{
	1: "START",
	2: "CONTINUE",
	3: "STOP",
}
var Query_QueryType_value = map[string]int32{
	"START":    1,
	"CONTINUE": 2,
	"STOP":     3,
}

func (x Query_QueryType) Enum() *Query_QueryType {
	p := new(Query_QueryType)
	*p = x
	return p
}
func (x Query_QueryType) String() string {
	return proto.EnumName(Query_QueryType_name, int32(x))
}
func (x Query_QueryType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Query_QueryType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Query_QueryType_value, data, "Query_QueryType")
	if err != nil {
		return err
	}
	*x = Query_QueryType(value)
	return nil
}

type Frame_FrameType int32

const (
	Frame_POS Frame_FrameType = 1
	Frame_OPT Frame_FrameType = 2
)

var Frame_FrameType_name = map[int32]string{
	1: "POS",
	2: "OPT",
}
var Frame_FrameType_value = map[string]int32{
	"POS": 1,
	"OPT": 2,
}

func (x Frame_FrameType) Enum() *Frame_FrameType {
	p := new(Frame_FrameType)
	*p = x
	return p
}
func (x Frame_FrameType) String() string {
	return proto.EnumName(Frame_FrameType_name, int32(x))
}
func (x Frame_FrameType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Frame_FrameType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Frame_FrameType_value, data, "Frame_FrameType")
	if err != nil {
		return err
	}
	*x = Frame_FrameType(value)
	return nil
}

type Response_ResponseType int32

const (
	Response_SUCCESS_ATOM     Response_ResponseType = 1
	Response_SUCCESS_SEQUENCE Response_ResponseType = 2
	Response_SUCCESS_PARTIAL  Response_ResponseType = 3
	Response_CLIENT_ERROR     Response_ResponseType = 16
	Response_COMPILE_ERROR    Response_ResponseType = 17
	Response_RUNTIME_ERROR    Response_ResponseType = 18
)

var Response_ResponseType_name = map[int32]string{
	1:  "SUCCESS_ATOM",
	2:  "SUCCESS_SEQUENCE",
	3:  "SUCCESS_PARTIAL",
	16: "CLIENT_ERROR",
	17: "COMPILE_ERROR",
	18: "RUNTIME_ERROR",
}
var Response_ResponseType_value = map[string]int32{
	"SUCCESS_ATOM":     1,
	"SUCCESS_SEQUENCE": 2,
	"SUCCESS_PARTIAL":  3,
	"CLIENT_ERROR":     16,
	"COMPILE_ERROR":    17,
	"RUNTIME_ERROR":    18,
}

func (x Response_ResponseType) Enum() *Response_ResponseType {
	p := new(Response_ResponseType)
	*p = x
	return p
}
func (x Response_ResponseType) String() string {
	return proto.EnumName(Response_ResponseType_name, int32(x))
}
func (x Response_ResponseType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Response_ResponseType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Response_ResponseType_value, data, "Response_ResponseType")
	if err != nil {
		return err
	}
	*x = Response_ResponseType(value)
	return nil
}

type Datum_DatumType int32

const (
	Datum_R_NULL   Datum_DatumType = 1
	Datum_R_BOOL   Datum_DatumType = 2
	Datum_R_NUM    Datum_DatumType = 3
	Datum_R_STR    Datum_DatumType = 4
	Datum_R_ARRAY  Datum_DatumType = 5
	Datum_R_OBJECT Datum_DatumType = 6
)

var Datum_DatumType_name = map[int32]string{
	1: "R_NULL",
	2: "R_BOOL",
	3: "R_NUM",
	4: "R_STR",
	5: "R_ARRAY",
	6: "R_OBJECT",
}
var Datum_DatumType_value = map[string]int32{
	"R_NULL":   1,
	"R_BOOL":   2,
	"R_NUM":    3,
	"R_STR":    4,
	"R_ARRAY":  5,
	"R_OBJECT": 6,
}

func (x Datum_DatumType) Enum() *Datum_DatumType {
	p := new(Datum_DatumType)
	*p = x
	return p
}
func (x Datum_DatumType) String() string {
	return proto.EnumName(Datum_DatumType_name, int32(x))
}
func (x Datum_DatumType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Datum_DatumType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Datum_DatumType_value, data, "Datum_DatumType")
	if err != nil {
		return err
	}
	*x = Datum_DatumType(value)
	return nil
}

type Term_TermType int32

const (
	Term_DATUM              Term_TermType = 1
	Term_MAKE_ARRAY         Term_TermType = 2
	Term_MAKE_OBJ           Term_TermType = 3
	Term_VAR                Term_TermType = 10
	Term_JAVASCRIPT         Term_TermType = 11
	Term_ERROR              Term_TermType = 12
	Term_IMPLICIT_VAR       Term_TermType = 13
	Term_DB                 Term_TermType = 14
	Term_TABLE              Term_TermType = 15
	Term_GET                Term_TermType = 16
	Term_EQ                 Term_TermType = 17
	Term_NE                 Term_TermType = 18
	Term_LT                 Term_TermType = 19
	Term_LE                 Term_TermType = 20
	Term_GT                 Term_TermType = 21
	Term_GE                 Term_TermType = 22
	Term_NOT                Term_TermType = 23
	Term_ADD                Term_TermType = 24
	Term_SUB                Term_TermType = 25
	Term_MUL                Term_TermType = 26
	Term_DIV                Term_TermType = 27
	Term_MOD                Term_TermType = 28
	Term_APPEND             Term_TermType = 29
	Term_SLICE              Term_TermType = 30
	Term_SKIP               Term_TermType = 70
	Term_LIMIT              Term_TermType = 71
	Term_GETATTR            Term_TermType = 31
	Term_CONTAINS           Term_TermType = 32
	Term_PLUCK              Term_TermType = 33
	Term_WITHOUT            Term_TermType = 34
	Term_MERGE              Term_TermType = 35
	Term_BETWEEN            Term_TermType = 36
	Term_REDUCE             Term_TermType = 37
	Term_MAP                Term_TermType = 38
	Term_FILTER             Term_TermType = 39
	Term_CONCATMAP          Term_TermType = 40
	Term_ORDERBY            Term_TermType = 41
	Term_DISTINCT           Term_TermType = 42
	Term_COUNT              Term_TermType = 43
	Term_UNION              Term_TermType = 44
	Term_NTH                Term_TermType = 45
	Term_GROUPED_MAP_REDUCE Term_TermType = 46
	Term_GROUPBY            Term_TermType = 47
	Term_INNER_JOIN         Term_TermType = 48
	Term_OUTER_JOIN         Term_TermType = 49
	Term_EQ_JOIN            Term_TermType = 50
	Term_ZIP                Term_TermType = 72
	Term_COERCE_TO          Term_TermType = 51
	Term_TYPEOF             Term_TermType = 52
	Term_UPDATE             Term_TermType = 53
	Term_DELETE             Term_TermType = 54
	Term_REPLACE            Term_TermType = 55
	Term_INSERT             Term_TermType = 56
	Term_DB_CREATE          Term_TermType = 57
	Term_DB_DROP            Term_TermType = 58
	Term_DB_LIST            Term_TermType = 59
	Term_TABLE_CREATE       Term_TermType = 60
	Term_TABLE_DROP         Term_TermType = 61
	Term_TABLE_LIST         Term_TermType = 62
	Term_FUNCALL            Term_TermType = 64
	Term_BRANCH             Term_TermType = 65
	Term_ANY                Term_TermType = 66
	Term_ALL                Term_TermType = 67
	Term_FOREACH            Term_TermType = 68
	Term_FUNC               Term_TermType = 69
	Term_ASC                Term_TermType = 73
	Term_DESC               Term_TermType = 74
)

var Term_TermType_name = map[int32]string{
	1:  "DATUM",
	2:  "MAKE_ARRAY",
	3:  "MAKE_OBJ",
	10: "VAR",
	11: "JAVASCRIPT",
	12: "ERROR",
	13: "IMPLICIT_VAR",
	14: "DB",
	15: "TABLE",
	16: "GET",
	17: "EQ",
	18: "NE",
	19: "LT",
	20: "LE",
	21: "GT",
	22: "GE",
	23: "NOT",
	24: "ADD",
	25: "SUB",
	26: "MUL",
	27: "DIV",
	28: "MOD",
	29: "APPEND",
	30: "SLICE",
	70: "SKIP",
	71: "LIMIT",
	31: "GETATTR",
	32: "CONTAINS",
	33: "PLUCK",
	34: "WITHOUT",
	35: "MERGE",
	36: "BETWEEN",
	37: "REDUCE",
	38: "MAP",
	39: "FILTER",
	40: "CONCATMAP",
	41: "ORDERBY",
	42: "DISTINCT",
	43: "COUNT",
	44: "UNION",
	45: "NTH",
	46: "GROUPED_MAP_REDUCE",
	47: "GROUPBY",
	48: "INNER_JOIN",
	49: "OUTER_JOIN",
	50: "EQ_JOIN",
	72: "ZIP",
	51: "COERCE_TO",
	52: "TYPEOF",
	53: "UPDATE",
	54: "DELETE",
	55: "REPLACE",
	56: "INSERT",
	57: "DB_CREATE",
	58: "DB_DROP",
	59: "DB_LIST",
	60: "TABLE_CREATE",
	61: "TABLE_DROP",
	62: "TABLE_LIST",
	64: "FUNCALL",
	65: "BRANCH",
	66: "ANY",
	67: "ALL",
	68: "FOREACH",
	69: "FUNC",
	73: "ASC",
	74: "DESC",
}
var Term_TermType_value = map[string]int32{
	"DATUM":              1,
	"MAKE_ARRAY":         2,
	"MAKE_OBJ":           3,
	"VAR":                10,
	"JAVASCRIPT":         11,
	"ERROR":              12,
	"IMPLICIT_VAR":       13,
	"DB":                 14,
	"TABLE":              15,
	"GET":                16,
	"EQ":                 17,
	"NE":                 18,
	"LT":                 19,
	"LE":                 20,
	"GT":                 21,
	"GE":                 22,
	"NOT":                23,
	"ADD":                24,
	"SUB":                25,
	"MUL":                26,
	"DIV":                27,
	"MOD":                28,
	"APPEND":             29,
	"SLICE":              30,
	"SKIP":               70,
	"LIMIT":              71,
	"GETATTR":            31,
	"CONTAINS":           32,
	"PLUCK":              33,
	"WITHOUT":            34,
	"MERGE":              35,
	"BETWEEN":            36,
	"REDUCE":             37,
	"MAP":                38,
	"FILTER":             39,
	"CONCATMAP":          40,
	"ORDERBY":            41,
	"DISTINCT":           42,
	"COUNT":              43,
	"UNION":              44,
	"NTH":                45,
	"GROUPED_MAP_REDUCE": 46,
	"GROUPBY":            47,
	"INNER_JOIN":         48,
	"OUTER_JOIN":         49,
	"EQ_JOIN":            50,
	"ZIP":                72,
	"COERCE_TO":          51,
	"TYPEOF":             52,
	"UPDATE":             53,
	"DELETE":             54,
	"REPLACE":            55,
	"INSERT":             56,
	"DB_CREATE":          57,
	"DB_DROP":            58,
	"DB_LIST":            59,
	"TABLE_CREATE":       60,
	"TABLE_DROP":         61,
	"TABLE_LIST":         62,
	"FUNCALL":            64,
	"BRANCH":             65,
	"ANY":                66,
	"ALL":                67,
	"FOREACH":            68,
	"FUNC":               69,
	"ASC":                73,
	"DESC":               74,
}

func (x Term_TermType) Enum() *Term_TermType {
	p := new(Term_TermType)
	*p = x
	return p
}
func (x Term_TermType) String() string {
	return proto.EnumName(Term_TermType_name, int32(x))
}
func (x Term_TermType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Term_TermType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Term_TermType_value, data, "Term_TermType")
	if err != nil {
		return err
	}
	*x = Term_TermType(value)
	return nil
}

type VersionDummy struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *VersionDummy) Reset()         { *this = VersionDummy{} }
func (this *VersionDummy) String() string { return proto.CompactTextString(this) }
func (*VersionDummy) ProtoMessage()       {}

type Query struct {
	Type             *Query_QueryType   `protobuf:"varint,1,opt,name=type,enum=Query_QueryType" json:"type,omitempty"`
	Query            *Term              `protobuf:"bytes,2,opt,name=query" json:"query,omitempty"`
	Token            *int64             `protobuf:"varint,3,opt,name=token" json:"token,omitempty"`
	Noreply          *bool              `protobuf:"varint,4,opt,name=noreply,def=0" json:"noreply,omitempty"`
	GlobalOptargs    []*Query_AssocPair `protobuf:"bytes,6,rep,name=global_optargs" json:"global_optargs,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (this *Query) Reset()         { *this = Query{} }
func (this *Query) String() string { return proto.CompactTextString(this) }
func (*Query) ProtoMessage()       {}

const Default_Query_Noreply bool = false

func (this *Query) GetType() Query_QueryType {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

func (this *Query) GetQuery() *Term {
	if this != nil {
		return this.Query
	}
	return nil
}

func (this *Query) GetToken() int64 {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return 0
}

func (this *Query) GetNoreply() bool {
	if this != nil && this.Noreply != nil {
		return *this.Noreply
	}
	return Default_Query_Noreply
}

func (this *Query) GetGlobalOptargs() []*Query_AssocPair {
	if this != nil {
		return this.GlobalOptargs
	}
	return nil
}

type Query_AssocPair struct {
	Key              *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Val              *Term   `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Query_AssocPair) Reset()         { *this = Query_AssocPair{} }
func (this *Query_AssocPair) String() string { return proto.CompactTextString(this) }
func (*Query_AssocPair) ProtoMessage()       {}

func (this *Query_AssocPair) GetKey() string {
	if this != nil && this.Key != nil {
		return *this.Key
	}
	return ""
}

func (this *Query_AssocPair) GetVal() *Term {
	if this != nil {
		return this.Val
	}
	return nil
}

type Frame struct {
	Type             *Frame_FrameType `protobuf:"varint,1,opt,name=type,enum=Frame_FrameType" json:"type,omitempty"`
	Pos              *int64           `protobuf:"varint,2,opt,name=pos" json:"pos,omitempty"`
	Opt              *string          `protobuf:"bytes,3,opt,name=opt" json:"opt,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (this *Frame) Reset()         { *this = Frame{} }
func (this *Frame) String() string { return proto.CompactTextString(this) }
func (*Frame) ProtoMessage()       {}

func (this *Frame) GetType() Frame_FrameType {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

func (this *Frame) GetPos() int64 {
	if this != nil && this.Pos != nil {
		return *this.Pos
	}
	return 0
}

func (this *Frame) GetOpt() string {
	if this != nil && this.Opt != nil {
		return *this.Opt
	}
	return ""
}

type Backtrace struct {
	Frames           []*Frame `protobuf:"bytes,1,rep,name=frames" json:"frames,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *Backtrace) Reset()         { *this = Backtrace{} }
func (this *Backtrace) String() string { return proto.CompactTextString(this) }
func (*Backtrace) ProtoMessage()       {}

func (this *Backtrace) GetFrames() []*Frame {
	if this != nil {
		return this.Frames
	}
	return nil
}

type Response struct {
	Type             *Response_ResponseType `protobuf:"varint,1,opt,name=type,enum=Response_ResponseType" json:"type,omitempty"`
	Token            *int64                 `protobuf:"varint,2,opt,name=token" json:"token,omitempty"`
	Response         []*Datum               `protobuf:"bytes,3,rep,name=response" json:"response,omitempty"`
	Backtrace        *Backtrace             `protobuf:"bytes,4,opt,name=backtrace" json:"backtrace,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (this *Response) Reset()         { *this = Response{} }
func (this *Response) String() string { return proto.CompactTextString(this) }
func (*Response) ProtoMessage()       {}

func (this *Response) GetType() Response_ResponseType {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

func (this *Response) GetToken() int64 {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return 0
}

func (this *Response) GetResponse() []*Datum {
	if this != nil {
		return this.Response
	}
	return nil
}

func (this *Response) GetBacktrace() *Backtrace {
	if this != nil {
		return this.Backtrace
	}
	return nil
}

type Datum struct {
	Type             *Datum_DatumType          `protobuf:"varint,1,opt,name=type,enum=Datum_DatumType" json:"type,omitempty"`
	RBool            *bool                     `protobuf:"varint,2,opt,name=r_bool" json:"r_bool,omitempty"`
	RNum             *float64                  `protobuf:"fixed64,3,opt,name=r_num" json:"r_num,omitempty"`
	RStr             *string                   `protobuf:"bytes,4,opt,name=r_str" json:"r_str,omitempty"`
	RArray           []*Datum                  `protobuf:"bytes,5,rep,name=r_array" json:"r_array,omitempty"`
	RObject          []*Datum_AssocPair        `protobuf:"bytes,6,rep,name=r_object" json:"r_object,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (this *Datum) Reset()         { *this = Datum{} }
func (this *Datum) String() string { return proto.CompactTextString(this) }
func (*Datum) ProtoMessage()       {}

var extRange_Datum = []proto.ExtensionRange{
	{10000, 20000},
}

func (*Datum) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Datum
}
func (this *Datum) ExtensionMap() map[int32]proto.Extension {
	if this.XXX_extensions == nil {
		this.XXX_extensions = make(map[int32]proto.Extension)
	}
	return this.XXX_extensions
}

func (this *Datum) GetType() Datum_DatumType {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

func (this *Datum) GetRBool() bool {
	if this != nil && this.RBool != nil {
		return *this.RBool
	}
	return false
}

func (this *Datum) GetRNum() float64 {
	if this != nil && this.RNum != nil {
		return *this.RNum
	}
	return 0
}

func (this *Datum) GetRStr() string {
	if this != nil && this.RStr != nil {
		return *this.RStr
	}
	return ""
}

func (this *Datum) GetRArray() []*Datum {
	if this != nil {
		return this.RArray
	}
	return nil
}

func (this *Datum) GetRObject() []*Datum_AssocPair {
	if this != nil {
		return this.RObject
	}
	return nil
}

type Datum_AssocPair struct {
	Key              *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Val              *Datum  `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Datum_AssocPair) Reset()         { *this = Datum_AssocPair{} }
func (this *Datum_AssocPair) String() string { return proto.CompactTextString(this) }
func (*Datum_AssocPair) ProtoMessage()       {}

func (this *Datum_AssocPair) GetKey() string {
	if this != nil && this.Key != nil {
		return *this.Key
	}
	return ""
}

func (this *Datum_AssocPair) GetVal() *Datum {
	if this != nil {
		return this.Val
	}
	return nil
}

type Term struct {
	Type             *Term_TermType            `protobuf:"varint,1,opt,name=type,enum=Term_TermType" json:"type,omitempty"`
	Datum            *Datum                    `protobuf:"bytes,2,opt,name=datum" json:"datum,omitempty"`
	Args             []*Term                   `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	Optargs          []*Term_AssocPair         `protobuf:"bytes,4,rep,name=optargs" json:"optargs,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (this *Term) Reset()         { *this = Term{} }
func (this *Term) String() string { return proto.CompactTextString(this) }
func (*Term) ProtoMessage()       {}

var extRange_Term = []proto.ExtensionRange{
	{10000, 20000},
}

func (*Term) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Term
}
func (this *Term) ExtensionMap() map[int32]proto.Extension {
	if this.XXX_extensions == nil {
		this.XXX_extensions = make(map[int32]proto.Extension)
	}
	return this.XXX_extensions
}

func (this *Term) GetType() Term_TermType {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

func (this *Term) GetDatum() *Datum {
	if this != nil {
		return this.Datum
	}
	return nil
}

func (this *Term) GetArgs() []*Term {
	if this != nil {
		return this.Args
	}
	return nil
}

func (this *Term) GetOptargs() []*Term_AssocPair {
	if this != nil {
		return this.Optargs
	}
	return nil
}

type Term_AssocPair struct {
	Key              *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Val              *Term   `protobuf:"bytes,2,opt,name=val" json:"val,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Term_AssocPair) Reset()         { *this = Term_AssocPair{} }
func (this *Term_AssocPair) String() string { return proto.CompactTextString(this) }
func (*Term_AssocPair) ProtoMessage()       {}

func (this *Term_AssocPair) GetKey() string {
	if this != nil && this.Key != nil {
		return *this.Key
	}
	return ""
}

func (this *Term_AssocPair) GetVal() *Term {
	if this != nil {
		return this.Val
	}
	return nil
}

func init() {
	proto.RegisterEnum("VersionDummy_Version", VersionDummy_Version_name, VersionDummy_Version_value)
	proto.RegisterEnum("Query_QueryType", Query_QueryType_name, Query_QueryType_value)
	proto.RegisterEnum("Frame_FrameType", Frame_FrameType_name, Frame_FrameType_value)
	proto.RegisterEnum("Response_ResponseType", Response_ResponseType_name, Response_ResponseType_value)
	proto.RegisterEnum("Datum_DatumType", Datum_DatumType_name, Datum_DatumType_value)
	proto.RegisterEnum("Term_TermType", Term_TermType_name, Term_TermType_value)
}
